# Generated by Django 5.1.7 on 2025-03-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_form', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlightItinerary',
        ),
    ]
