# Generated by Django 5.1.7 on 2025-03-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_form', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightitinerary',
            name='day_1_activity',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='day_2_activity',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='day_3_activity',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='day_4_activity',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='day_5_activity',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='day_6_activity',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='day_7_activity',
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='check_in_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الدخول'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='check_out_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الخروج'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المدينة'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم العميل'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الفندق'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='hotel_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الفندق'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='الملاحظات'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='number_of_nights',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الليالي'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='package_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم البكدج'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='room_details',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل الغرفة'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='tour_day_1_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ اليوم الأول'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='tour_day_1_details',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل اليوم الأول'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='tour_day_2_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ اليوم الثاني'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='tour_day_2_details',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل اليوم الثاني'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='tour_day_3_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ اليوم الثالث'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='tour_day_3_details',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل اليوم الثالث'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='tour_day_4_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ اليوم الرابع'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='tour_day_4_details',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل اليوم الرابع'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='tour_day_5_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ اليوم الخامس'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='tour_day_5_details',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل اليوم الخامس'),
        ),
    ]
