# Generated by Django 5.1.7 on 2025-03-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_form', '0004_remove_flightitinerary_day_1_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightitinerary',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='hotel_name',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='hotel_url',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='number_of_nights',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='package_number',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='room_details',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='tour_day_1_date',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='tour_day_1_details',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='tour_day_2_date',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='tour_day_2_details',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='tour_day_3_date',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='tour_day_3_details',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='tour_day_4_date',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='tour_day_4_details',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='tour_day_5_date',
        ),
        migrations.RemoveField(
            model_name='flightitinerary',
            name='tour_day_5_details',
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='day_1_activity',
            field=models.TextField(blank=True, null=True, verbose_name='النشاط في اليوم الأول'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='day_2_activity',
            field=models.TextField(blank=True, null=True, verbose_name='النشاط في اليوم الثاني'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='day_3_activity',
            field=models.TextField(blank=True, null=True, verbose_name='النشاط في اليوم الثالث'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='day_4_activity',
            field=models.TextField(blank=True, null=True, verbose_name='النشاط في اليوم الرابع'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='day_5_activity',
            field=models.TextField(blank=True, null=True, verbose_name='النشاط في اليوم الخامس'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='day_6_activity',
            field=models.TextField(blank=True, null=True, verbose_name='النشاط في اليوم السادس'),
        ),
        migrations.AddField(
            model_name='flightitinerary',
            name='day_7_activity',
            field=models.TextField(blank=True, null=True, verbose_name='النشاط في اليوم السابع'),
        ),
    ]
