# Generated by Django 5.1.7 on 2025-03-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_form', '0005_remove_flightitinerary_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightitinerary',
            name='Passport_Number',
            field=models.CharField(default='', max_length=20, verbose_name='رقم الجواز'),
            preserve_default=False,
        ),
    ]
